server:
  port: 9080
spring:
  application:
    name: Eureka-Server
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9080/eureka/
  server:
    enable-self-preservation: false