server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:9080/eureka/

spring:
  application:
    name: Server-Consumer
